name: womensafty
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #tools
  dio: ^3.0.10
  intl: ^0.16.1
  form_field_validator: ^1.0.1

  #ui
  font_awesome_flutter: ^8.11.0
  cupertino_icons: ^1.0.0

  #Chart
  fl_chart: ^0.12.3

  #firebase
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1

  #Architecture
  stacked: 1.9.1+2
  stacked_services: 0.6.7
  observable_ish: ^2.1.5
  responsive_builder: ^0.3.0
  get_it: ^5.0.6
  auto_route: ^0.6.1
  injectable: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 1.1.0
  auto_route_generator: 0.6.10
  build_runner: 1.11.1
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
